version: "3"

services:
  gateway:
    hostname: gateway
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - library
      - rating
      - reservation
    environment:
      - LIB_SERVICE_URL=library:8060
      - RATING_SERVICE_URL=rating:8050
      - RESERVATION_SERVICE_URL=reservation:8070

  library:
    hostname: library
    build:
      context: ./services/library
      dockerfile: Dockerfile
    ports:
      - "8060:8060"

  reservation:
    hostname: reservation
    build:
      context: ./services/reservation
      dockerfile: Dockerfile
    ports:
      - "8070:8070"

  rating:
    hostname: rating
    build:
      context: ./services/rating
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
