version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  bonus:
    image: bonus
    container_name: bonus
    restart: on-failure
    build:
      context: src
      dockerfile: bonus/Dockerfile
    ports:
      - "8050:8050"
    depends_on:
      - postgres

  flight:
    image: flight
    container_name: flight
    restart: on-failure
    build:
      context: src
      dockerfile: flight/Dockerfile
    ports:
      - "8060:8060"
    depends_on:
      - postgres

  ticket:
    image: ticket
    container_name: ticket
    restart: on-failure
    build:
      context: src
      dockerfile: ticket/Dockerfile
    ports:
      - "8070:8070"
    depends_on:
      - postgres

  gateway:
    image: gateway
    container_name: gateway
    restart: on-failure
    build:
      context: src
      dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  db-data:
