version: "3"
services:
  bonus:
    image: bonus
    container_name: bonus
    restart: on-failure
    build:
      context: src/bonus
      dockerfile: Dockerfile
    ports:
      - "8050:8050"

  flight:
    image: flight
    container_name: flight
    restart: on-failure
    build:
      context: src/flight
      dockerfile: Dockerfile
    ports:
      - "8060:8060"

  ticket:
    image: ticket
    container_name: ticket
    restart: on-failure
    build:
      context: src/ticket
      dockerfile: Dockerfile
    ports:
      - "8070:8070"

  gateway:
    image: gateway
    container_name: gateway
    restart: on-failure
    build:
      context: src/gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

volumes:
  db-data:
