version: "3"
services:
  gateway:
      image: gateway
      container_name: gateway
      restart: on-failure
      build:
        context: src/gateway
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
  bonus:
    image: bonus
    container_name: bonus
    restart: on-failure
    build:
      context: src/bonus
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    depends_on:
      - gateway

  flight:
    image: flight
    container_name: flight
    restart: on-failure
    build:
      context: src/flight
      dockerfile: Dockerfile
    ports:
      - "8060:8060"
    depends_on:
      - gateway


  ticket:
    image: ticket
    container_name: ticket
    restart: on-failure
    build:
      context: src/ticket
      dockerfile: Dockerfile
    ports:
      - "8070:8070"
    depends_on:
      - gateway
